FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "MilkMaster.Subscriber/MilkMaster.Subscriber.csproj"

FROM build AS publish
RUN dotnet publish "MilkMaster.Subscriber/MilkMaster.Subscriber.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MilkMaster.Subscriber.dll"]
